### ISSUE TITLE
[HIPIFY] Both hipify-perl and hipify-clang unnecessarily warn on atomicAdd

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1490]
hipify-perl prints unnecessary warnings for atomicAdd.

**Comment by emankov** [comment]
Is it a device function in your case? Please provide a test case.

**Comment by Kaveh01** [comment]
@emankov 
I attached the example.
[1490.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3675319/1490.tar.gz)

**Comment by emankov** [comment]
hipify-clang warns too:

`\AppData\Local\Temp\atomicAdd.cu-31d983.hip:9:9: warning: CUDA identifier is unsupported in HIP.                                                                                                                                                                                                     atomicAdd(&a[i], 1.0f);`                                                                                                                                                                                                                                                                                  

`^`                                                                                                                                                                                                                                                                                                   

`1 warning generated when compiling for host.`

It is because a device function `atomicAdd` is marked as `HIP_UNSUPPORTED`.
So it should be fixed as long as populating the list of supported device atomic functions.

**Comment by emankov** [comment]
Should be fixed, please check with both tools. Thanks!

**Comment by Kaveh01** [comment]
Thanks. It works well.
