### ISSUE TITLE
Making an Arch User Repository (AUR) Package

### ISSUE THREAD

**Issue by JPenuchot** [ROCm-Developer-Tools/HIP#2105]
Hey everyone,

I figured making a package for the Arch User Repository (AUR) might be very helpful to bring HIP to more people by making the installation straightforward for Arch/Manjaro users. It shouldn't be too hard since Arch packages are rather minimalist ([here's the doc in the Arch wiki](https://wiki.archlinux.org/index.php/Creating_packages)).

I'd gladly do the effort and start working on it as soon as I have a proper internet connection, but the issue is here in case someone more familiar with Arch packages wants to take the lead.

Regards,
Jules

PS: There already is an [HIP package](https://aur.archlinux.org/packages/hip-amdgpu-pro/) but it's only for the runtime, not the compiler.

**Comment by acxz** [comment]
Hey @JPenuchot The Arch community has been doing some work at https://github.com/rocm-arch/rocm-arch to get a bunch of ROCm packages working. Feel free to check it out. As of right now we have many ROCm 3.5 packages compiling however we only officially support Arch and Arch-repo compatible operating systems like [EndeavourOS](https://endeavouros.com/). There have been some reports with Manjaro users stating the packages do not work for them, since Manjaro is not Arch-repo compatible.

I believe this issue can be closed.

**Comment by JPenuchot** [comment]
Hey, thanks a lot I didn't know about that project, I'll try it out as soon as I can
