### ISSUE TITLE
[HIPIFY] Inserted hip include should ideally be after include guard

### ISSUE THREAD

**Issue by ChrisKitching** [ROCm-Developer-Tools/HIP#211]
When hipify inserts the `#include <hip/hip_runtime.h>` line into a header, it would be best to do it after any existing `#pragma once` or traditional include guard. Saves the user a bit of tedious cleanup.

One elegant way to implement this might be to replace the current insertion behaviour with logic to _replace_ appropriate CUDA `#include` lines with hip ones. Unilaterally inserting this include into every file which you've made changes to is probably overkill - isn't it enough to replace `#include <cuda>` with the hip include?

**Comment by emankov** [comment]
It was done so intentionally, because cuda header might be absent at all in a source and NVCC correctly compile such source. But this particular case doesn't negate the necessity of correctly handling of other cases. So the correct behaviour looks like as following:
1. Replace existing  #include <cuda> or #include <cuda_runtime.h>, m.b. others (taking into accout multiple includes).
2. Insert #include <hip/hip_runtime.h> on an appropriate line in case of absence of cuda header includes.

Chris, I've just assigned the issue on myself.

**Comment by ChrisKitching** [comment]
> because cuda header might be absent at all in a source and NVCC correctly compile such source.

Oh right. I forgot about this - NVCC implicitly includes a bunch of cuda stuff, doesn't it? (and clang does the same in cuda mode for compatibility). That explains it.

**Comment by emankov** [comment]
The last case to cover.
`#ifndef #define ... #endif` guard for the entire file. In this case HIP main include should be placed just after `#ifndef`, or after `#pragma once`, if it is also presented.

**Comment by emankov** [comment]
Fixed by #1282
