### ISSUE TITLE
HIP API launch performance when using hipMemcpyAsync

### ISSUE THREAD

**Issue by learner321** [ROCm-Developer-Tools/HIP#2291]
In my application, I find that the performance is low when I use the `hipMemcpyAsync` in ROCm4.0.1. It seems that the `hipMemcpyAsync`  blocked the API launch in other stream. `hipMemcpywithStream`  also doesn't work as  expected.  The rocprof time is show below.
![image](https://user-images.githubusercontent.com/23622862/121511855-ac628e80-ca1b-11eb-855a-f1696b8af535.png)
Then I change the API from `hipMemcpyAsync` to `hipMemcpy2DAsync`. It seems that the pipeline overlaps better. But Why the different copy stream can overlap? There is just one pcie connected with GPU in my computer.
![image](https://user-images.githubusercontent.com/23622862/121511915-bdab9b00-ca1b-11eb-8226-9f496d54bf5d.png)
Thanks :)

**Comment by learner321** [comment]
It seems unpinned memory causes the blocking of `hipMemcpyAsync`. Why.

**Comment by mangupta** [comment]
This is to be expected. For unpinned memory since the application has allocated the host buffer outside the HIP runtime, the runtime does not know if the memory remains valid till the async memcpy is completed. Hence it treats the memcpy as synchronous.

In fact CUDA documentation for [memcpy](https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-async) states that the "Async" suffix in memcpy APIs is a misnomer and the actual behavior depends on the arguments.

**Comment by learner321** [comment]
Thanks. How about the behavior of hipMemcpy2DAsync. It seems async. @mangupta

**Comment by learner321** [comment]
I find that if data size is smaller than 64KB, memcpy is asynchronous for pageable memory in CUDA.  Is there a mechanism like this in ROCm.

**Comment by ppanchad-amd** [comment]
@learner321 Do you still need assistance with this ticket? If not, please close. Thanks!

**Comment by learner321** [comment]
您的邮件已收到！！！

**Comment by ppanchad-amd** [comment]
@learner321 Closing ticket. Please re-open if you still see the issue with the latest ROCm 6.1.1 Thanks!

**Comment by learner321** [comment]
您的邮件已收到！！！
