### ISSUE TITLE
hip-runtime-nvidia and hip-devel packages missing

### ISSUE THREAD

**Issue by GeorgeQ-Q** [ROCm-Developer-Tools/HIP#2321]
![image](https://user-images.githubusercontent.com/26531602/130205836-576c0a2c-b8c8-4db2-8b99-01323767ba57.png)

These two packages are not under Key: https://repo.radeon.com/rocm/rocm.gpg.key. Are they missing or a different key is needed

best 
G

**Comment by lokitkhemka** [comment]
+1. I need help with this issue too. Lot of solutions that I followed simply corrupts my ubuntu installations. A simple straight-forward installation guide should help.

**Comment by tom-papatheodore** [comment]
Hello. I wanted to ping this issue to see if there has been any movement for the folks who originally submitted it... 

I notice that one of the packages listed above is different than one in the HIP Github: https://github.com/ROCm-Developer-Tools/HIP/blob/develop/INSTALL.md#nvidia-platform; specifically `hip-dev` instead of `hip-devel`. 

For the folks waiting on this, I see there are also installation instructions to build from source here (last updated in July - so fairly recently) that might be helpful: https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_build.md.
