### ISSUE TITLE
hipErrorSharedObjectInitFailed

### ISSUE THREAD

**Issue by shana34** [ROCm-Developer-Tools/HIP#2342]
Hi,
        I am writting some GCN assemble files recently. I refered to the GCN assemble guide on Rocm website. However, when I tried to generate 'a.co' file and load it by 'hipModuleLoad' API. I got 'hipErrorSharedObjectInitFailed', I don't know why this error arises.
       Below is the snapshots of the question:
![image](https://user-images.githubusercontent.com/22281195/132942151-4a12ed6e-a012-4c57-b9fa-4188d19c4c64.png)
![image](https://user-images.githubusercontent.com/22281195/132942155-ea7a008e-264b-42ca-9804-e32002ce4aa9.png)
       Thanks for kindly you.

**Comment by yxsamliu** [comment]
The assembly needs to have metadata https://llvm.org/docs/AMDGPUUsage.html#code-object-metadata

You may follow https://github.com/ROCm-Developer-Tools/HIP/tree/develop/samples/2_Cookbook/16_assembly_to_executable to modify an assembly generated from a HIP code to get the correct metadata instead of creating assembly from scratch.

**Comment by ppanchad-amd** [comment]
@shana34, Is this still an issue? If not, please close the ticket.  Thanks!
