### ISSUE TITLE
Provide a minimal installation for building HIP applications

### ISSUE THREAD

**Issue by Maetveis** [ROCm-Developer-Tools/HIP#2483]
The size of an installation for compiling hip applications on a rocm platform is quite large.

```sh
sudo apt install rocm-hip-runtime-dev
du -sh /opt/rocm-5.0.0/
```
Result:
```
3.6G	/opt/rocm-5.0.0/
```

Most of this (3.4G) is in `/opt/rocm/llvm` which includes many non-essential clang based tools like clang-repl (114MB), clang-scan-deps(100MB), clang-check(90MB) and clang-tidy. I dont think these tools are specialized for HIP so users can just install them from the distributions repositories if they are want to.

Expected result:
Something smaller: at most 500MB, for reference an installation of clang on ubuntu is around ~300MB

**Comment by Maxzor** [comment]
We are building official debian packages with llvm upstream, you might want to check that out in a few days/weeks :) https://salsa.debian.org/rocm-team/community/team-project#packaging-progress

**Comment by Maxzor** [comment]
https://github.com/ROCm-Developer-Tools/HIP/issues/2449

**Comment by ppanchad-amd** [comment]
@Maetveis Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by Maetveis** [comment]
This is still not resolved, actually it is worse now `/opt/rocm-6.0.2/` is 4.1G with **only** the `rocm-llvm` package installed.

The non essential clang tools are still there and they are still statically linked (which makes them huge).

**Comment by ppanchad-amd** [comment]
@Maetveis Internal ticket has been created to resolve this issue. Thanks!

**Comment by jamesxu2** [comment]
Hello @Maetveis, there is an ongoing effort to shrink the size of our install. As of ROCm 6.1, rocm-llvm was split into 2 packages:
1. rocm-llvm - required binaries for compilation
2. rocm-llvm-dev - optional binaries/headers for compiler/application developers

There's [another discussion on this issue here.](https://github.com/ROCm/ROCm/issues/2703)

Additional work in dynamically linking llvm into our components is in progress as well, which should reduce the install size. 

We hear your concerns regarding the current install size and I want to let you know that there's an ongoing effort to address it.
