### ISSUE TITLE
[ROCm 5.2] Some `hipMemcpy` array functions not presented in `hip_runtime_api.h`

### ISSUE THREAD

**Issue by emankov** [ROCm-Developer-Tools/HIP#2782]
But their implementations are in `hip_memory.cpp` of [hipamd](https://github.com/ROCm-Developer-Tools/hipamd).

Please, provide a declaration of `hipMemcpyArrayToArray`, `hipMemcpyFromArrayAsync`, and `hipMemcpyToArrayAsync` in `hip_runtime_api.h`.

**Comment by iassiour** [comment]
Hi @emankov  these functions are deprecated in cuda
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__DEPRECATED.html

As of cuda 12.1 the headers still exist but are declared as deprecated. 

Should the deprecated headers be added in this case or it would make more sense to add a note to advise that during hipification? In the latter case, I think the implementation in hip_memory.cpp is dangling and could be removed as well.

**Comment by iassiour** [comment]
It looks like hipify script already warns about hipMemcpyArrayToArray, hipMemcpyFromArrayAsync, and hipMemcpyToArrayAsync being deprecated. Since these functions are missing the headers I have raised a PR internally to remove their implementation from hip_memory.cpp. Changes should become visible in the next release. Closing the issue.
