### ISSUE TITLE
[docs] Link to HIP-API.pdf

### ISSUE THREAD

**Issue by ldrumm** [ROCm-Developer-Tools/HIP#3240]
The programming manual for "Managed Memory Allocation" [refers](https://github.com/ROCm-Developer-Tools/HIP/blob/3aad3723f20700002b770f04f83b3dafab00bd41/docs/user_guide/programming_manual.md?plain=1#L52) the user to `HIP-API.pdf`. I can't find it by searching the web nor my local system

Does it exist?

If it still exists, providing a direct link would help; if not, delete that reference

**Comment by ppanchad-amd** [comment]
@ldrumm Internal ticket has been created to take a look at this issue. Thanks!

**Comment by harkgill-amd** [comment]
Hi @ldrumm, the reference to `HIP-API.pdf` has since been removed from the Managed Memory Allocation section of the HIP Programming Manual. You can find the latest version of the manual [here](https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/programming_manual.html#managed-memory-allocation).
