### ISSUE TITLE
Inline asm  translation 

### ISSUE THREAD

**Issue by microyybar** [ROCm-Developer-Tools/HIP#3285]
How can I convert cuda code 
asm("bfe.u64 %0, %1, %2, %3;" : "=l"(z) : "l"(i), "r"(j), "r"(k)); 
to hip inline asm or normal amdgpu code?
Because invalid output constraint '=l' in hip  asm. There is no u64 reg constraint.

Env:  RX 6700 XT, gfx1031 , rocm5.4.2

**Comment by b-sumner** [comment]
I'd suggest using

extern "C" int __ockl_bfe_i32(int x, uint s, uint w);

and

extern "C" uint __ockl_bfe_u32(uint x, uint s, uint w);

where "x" is the value,  "s" is the shift amount, and "w" is the width.  Here "uint" == uint32_t.

**Comment by yxsamliu** [comment]
CUDA inline assembly uses nvptx. You can search bfe in nvptx manual https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#instruction-set.

asm("bfe.u64 %0, %1, %2, %3;" : "=l"(z) : "l"(i), "r"(j), "r"(k));

extract bitfield from i for bits starting at index j with width k, and store results in z.

HIP inline assembly uses amdgpu ISA. You can find amdgpu ISA manual at the end of https://llvm.org/docs/AMDGPUUsage.html#additional-documentation

In the RDNA2 ISA manual search bfe you can find RDNA2 has a corresponding instruction bfe.

HIP encourages using clang builtin instead of inline assembly if possible. clang builtin for amdgpu can be found at https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/BuiltinsAMDGPU.def

There is __builtin_amdgcn_ubfe for unsigned bit field extraction. search it for llvm-project github repo and you can find a sample using it.

**Comment by yxsamliu** [comment]
__ockl_bfe_u32 and __builtin_amdgcn_ubfe are equivalent. They generate the same ISA https://godbolt.org/z/j9nxexhTr

**Comment by b-sumner** [comment]
Yes, but using OCKL insulates you from any future ISA changes.  It will always work.

**Comment by ppanchad-amd** [comment]
@microyybar Is this issue resolved? If so, please close ticket. Thanks!
