### ISSUE TITLE
[Feature]: Add Radeon RX 7900 GRE support on Windows

### ISSUE THREAD

**Issue by rafrafek** [ROCm-Developer-Tools/HIP#3688]
### Suggestion Description

Hello, could you please consider adding support for AMD Radeon RX 7900 GRE on Windows? It is currently not listed as supported: https://rocm.docs.amd.com/projects/install-on-windows/en/develop/reference/system-requirements.html

### Operating System

Windows

### GPU

RX 7900 GRE

### ROCm Component

HIP SDK installation (Windows)

**Comment by harkgill-amd** [comment]
Hi @rafrafek, the 7900 GRE is not currently supported on the HIP SDK for Windows. "Supported" in this case simply means that there's no testing done internally to validate that the card works as intended with the HIP SDK. With that being said, the 7900 GRE is the same architecture as the 7900XT/XT (gfx1100) and may still work for most use cases. 

I'd recommend giving it a try on your end and reporting any issues that might arise. From there, we can determine if the issue is generic across all SKUs or if it's caused by the support status of the 7900 GRE specifically.

**Comment by rafrafek** [comment]
Hi @harkgill-amd, thank you for your reply. I went with the 7800 XT since it supports Windows, but I really wish it had Linux support too. Looks like only the 7900 XT and 7900 XTX officially work with Windows and Linux. I hope the 8800 XT will support both operating systems.

**Comment by cjatin** [comment]
7900 GRE is gfx1100, it should support ROCm.
