### ISSUE TITLE
amd_hip_fp16.h: candidate function not viable: call to __device__ function from __host__ function

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3690]
I am not sure if the issues were reported before.  

/opt/rocm-6.2.0/lib/llvm/bin/../../../include/hip/amd_detail/amd_hip_fp16.h:280:24: note: candidate function not viable: call to __device__ function from __host__ function
  280 |                 __half operator*(const __half& x, const __half& y)

/opt/rocm-6.2.0/lib/llvm/bin/../../../include/hip/amd_detail/amd_hip_fp16.h:287:24: note: candidate function not viable: call to __device__ function from __host__ function
  287 |                 __half operator/(const __half& x, const __half& y)
      |                        ^

**Comment by cjatin** [comment]
can you share sample as well.

**Comment by jinz2014** [comment]
https://github.com/zjin-lcf/HeCBench/tree/master/src/nlll-hip

**Comment by cjatin** [comment]
I think the issue is the attempt to use `*` operator for `__half` on host. Which on HIP is not supported. There is just `__device__` variants available: https://github.com/ROCm/clr/blob/c47f9dda5886b8062cad1b9c9736671241ab6f9a/hipamd/include/hip/amd_detail/amd_hip_fp16.h#L198

One thing you might need to do (for now) here is pass on `_Float16` for hosts and `__half` for device. Something like this: https://gist.github.com/cjatin/b92a5b51adc2e0e4a60d4ad7c4d2fdc2 (although there might be better design possible than what I wrote here)

I think we should add the host operators, will create a task for it internally to track and add these.

**Comment by jinz2014** [comment]
I will wait for the host operators. Thank you for the answer!

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@jinz2014 I agree with @cjatin the device type **half** must have been called in host function. So I checked your source, probably caused by the reference out computing in cpu side:

```
// call in cpu , run in cpu
driver<half, int>(argv);

// call in cpu , run in cpu
  reference<scalar_t, scalar_t, index_t>(
    &r_output, &r_total_weight,
    h_input, h_target, h_weights,
    size_average, nframe, n_classes, ignore_index);

 // call in cpu, run in cpu (it contains gpu kernel calling)
  #define EVAL(nThreads) \
  eval<scalar_t, index_t, nThreads>(nframe, n_classes, n_classes, \
                                    size_average, ignore_index, \
                                    r_output, r_total_weight, \
                                    h_input, h_weights, h_target, repeat)
```

The issue is obviously here:

```
// scalar_t = half
 reference<scalar_t, scalar_t, index_t>(
```

you are calling device type **half** in cpu function **reference**. That is not allowed.

**Comment by jinz2014** [comment]
Thank you for your comments on the example. You might run the nlll-cuda and nlll-sycl examples.
We understand the issue: "I think we should add the host operators, will create a task for it internally to track and add these".

**Comment by cjatin** [comment]
You folks might be interested in: https://github.com/ROCm/clr/commit/5122b8c999696f29523bf955e6347d0b06709cae

There are some bugs which I am fixing with __hisnan, but this should hopefully sort out the issue here.

**Comment by jinz2014** [comment]
Thanks. Does a host function exist (e.g., h2exp2) ?


            __half2 h2exp2(__half2 x)
            {
                return __half2{__ocml_exp2_2f16(x)};
            }

**Comment by cjatin** [comment]
Unfortunately no: https://docs.nvidia.com/cuda/cuda-math-api/cuda_math_api/group__CUDA__MATH____HALF2__FUNCTIONS.html#group__cuda__math____half2__functions_1gac5cda143ba8404d8fba64a4271ef2d60

**Comment by jinz2014** [comment]
I see; some math APIs are device functions only.
