### ISSUE TITLE
Installation instructions are circular

### ISSUE THREAD

**Issue by baryluk** [ROCm-Developer-Tools/HIP#803]
https://github.com/ROCm-Developer-Tools/HIP  , points to:

https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md
 , but it actually doesn't tell what to install (i.e. what are names of debian/ubuntu packages), and instead points to:

http://gpuopen.com/getting-started-with-boltzmann-components-platforms-installation/
, which is an article that doesn't actual tell how to install it. (and is over 2 years old) and points to:

https://rocm.github.io/ROCmInstall.html
, but it doesn't really correctly specify how to install HIP.

There is a link to HIP there, which points to:

https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/roc-1.9.x
Yet another repository?

It redirects eventually to:

https://github.com/ROCm-Developer-Tools/HIP/tree/roc-1.9.x

Madness.

The only thing about installation in the ROCmInstall.html, is `rocm-dkms` . Which (INCORRECTLY) depends on `rocm-dev`, which depends on `hip_hcc` (kind of correctly).

This should be pretty much reverse. I should just install `hip-hcc`, and it would pull needed dependencies (and suggest rocm-dkms), as it should be.

If you want some package that pulls ALL dependencies, just create a metapackage with proper dependencies.

And document it here, in the project installation, not 4 links forward.

(It is really frustrating, to see such great software be so hard to use because fragmented and duplicated documentation and messed up packaging).

**Comment by jlgreathouse** [comment]
Hi @baryluk 

Thank you for the report. You're absolutely right that our documentation could use improvement. This is pretty high on our todo list, and your reports are good input for focusing our efforts on the serious problems.

A lot of the documentation you're going through (e.g. the I[NSTALL.md for HIP](https://github.com/ROCm-Developer-Tools/HIP/blob/roc-1.9.x/INSTALL.md) that points to the gpuopen article) is somewhat old. At the time, we avoided just saying `apt install hip_hcc` because we needed users to install a great deal more software (including a fully custom monolithic Linux kernel). Things have improved since then (IMO) so we should probably revisit our various installations directions to clean them up in light of this. Now, if your kernel is new enough for your GPU, you should be able to just install user-level stuff using the command above to get a working HIP installation. If you are using an older kernel (or your kernel is not new enough to support your GPU -- or if you want some of the features offered by our driver) you may also need to install `rock-dkms`.

That being said, I believe that our packages do include a correct set of intra-ROCm dependencies to get HIP working on ROCm. (Setting aside your other reports on missing system-level dependencies that we hadn't sensitized due to testing on Ubuntu, where they were installed by default).

You mentioned that if we want a package that pulls dependencies, we should create a meta-package. Both `rocm-dkms` and `rocm-dev` are such the meta-packages. The former is meant to install both the kernel- and user-mode ROCm software, while the latter is meant to install just the user-mode ROCm software. The latter exists because, as mentioned above, you may not want or need to install the ROCK kernel driver on your OS but you still want the user-level "ROCm".
```
# rocm-dkms is a meta-package that installs the both the ROCK
# kernel driver (rock-dkms) and ROCm user-level components
# (the rocm-dev meta-package)
# rocm-dev is a meta-package that installs the user-level ROCm
# components (though not libraries. Many of those can be installed
# with the rocm-libs meta-package)
rocm-dkms
 |-- rock-dkms
 |-- rocm-dev
      |--hsa-rocr-dev
      |--hsa-ext-rocr-dev
      |--rocm-device-libs
      |--rocm-utils
      |--hcc
      |--hip_base
      |--hip_doc
      |--hip_hcc
      |--hip_samples
      |--rocm-smi
      |--hsakmt-roct
      |--hsakmt-roct-dev
      |--hsa-amd-aqlprofile
      |--comgr
      |--rocr_debug_agent
```

That said, if you don't want to directly install HIP for ROCm, you're right that `hip_hcc` is the package to do so. Following its dependencies, this should get the appropriate user-level software in place. It will not install `rock-dkms` as that is not a strict dependence of any of the user-level software.
```
hip_hcc                       # The version of HIP which compiles HIP code for ROCm
 |--hip_base
 |--hcc                       # It uses HCC to do this compilation
      |--hsa-rocr-dev         # The ROCr runtime
          |--hsakmt-roct-dev  # Headers for the Thunk kernel interface
              |--hsakmt-roct  # Thunk kernel interface
      |--hsa-ext-rocr-dev     # Closed source libraries for the ROCr runtime
      |--rocm-utils           # Meta-package for ROCM user-land "utilities"
          |--romcminfo        # Needed by HCC for rocm_agent_enumerator
          |--rocm-clang-ocl   # Not strictly needed by HCC
```

As such, this should install HIP, HCC, ROCr, the Thunk, and rocminfo. I believe this is a minimum but functional set of software to run HIP so long as you have a properly working kernel driver (whether upstream, or with a separately installed `rock-dkms`). I'll admit that HCC should probably depend directly on `rocminfo` instead of `rocm-utils`. I've been discussing such a patch internally already, in fact. :)

**Comment by baryluk** [comment]
I see. I was confused what the `rocm-dkms` even is. It appears it is not actually a DKMS package, but a meta package with all dependencies. This now make sense, and makes the existing install guides much more sense too me too, it is just the fact that it was named `rocm-dkms` very unfortunate. I was certain that rocm-dkms is a dkms module stuff for kernel, and rock-dkms some yet another kernel driver for something that is also required.

the meta package could have been just 'rocm` or `rocm-platform`, and the dkms package should be simply `rocm-dkms` (hopefully not even needed soon. I didn't use it on my 4.18 kernel, but afaik there are few features still in progress of upstreaming). 

BTW. I figured out how to install pieces by pieces what I need, and it works, and managed to install and test hcc and hip, by inspecting all the files, installing one by one, and figuring what are proper dependencies.

I am reporting, because I want ROCm to be a successful project, and not make other people be lost, especially if they are less technically versed than me.


I reported various issues with inter package dependencies to their respective repos. Almost none of packages has fully correct dependencies. Again, these are bugs to fix, not to fix my particular problem (because I can easily work it around and figure it out). I do not want to deal with these problems over and over again, on my dozens of computers or friends computers, etc.

**Comment by jlgreathouse** [comment]
Hi @baryluk 

I expect that the `rock-dkms` package will stick around. While we do want to get all of our needed modifications into upstream kernels, having a separate ROCm driver has some benefits:
- It allows us to support distros and releases that use kernels from before our code was upstreamed.
- It allows for new hardware support for older kernels. For instance, if you buy a brand new GPU next year, the kernel you are using right now may or may not include support for that new GPU. Rather than forcing new users onto bleeding edge kernels, having an optional module like `rock-dkms` allows users of older releases (or stability-focused distros) to use the new GPUs
- It allows us to include updated firmware that may include fixes done after a distro did their firmware snapshot.
- We can bring up new features faster in this driver, because we can release before they've gone through the full upstream vetting process.


I want to thank you for reporting all the stuff you have. I hope that my answers have not sounded dismissive. We do appreciate feedback like this -- this is exactly the kind of feedback we hope to get as part of opening up all our software.

A lot of my answers have been explaining things because these GitHub issues come up pretty highly on internet searches when people run into problems similar to yours. Hopefully they'll also find my answers useful. :) That said, your concerns have been heard and we are working to get "documentation updates" into our developers' busy schedules.

Your help pointing out dependency issues are also appreciated. I'll admit that we sometimes fall into the trap of "this list of dependencies work on my system, ship it". :)  Our packages *should* work on all of our officially supported distributions (Ubuntu 18.04, Ubuntu 16.04, CentOS/RHEL 7.4 and 7.5). You're right that a good list of dependencies would ease the burden of getting ROCm running on "unsupported" distros.

**Comment by baryluk** [comment]
Your packages mostly work, if you install the `rocm-dkms` thingy, because it basically pulls EVERYTHING into your system (plus hopefully libtinfo5 which might be already installed on some desktops). But if you ask to install only hip, or opencl runtime, it is very will install, but it will not work.

I understand different priorities during development.

Yeah, supporting newer hardware on older kernel / long term support machines, justifies keeping `rock-dkms` (`amdkfd-dkms` or something, would sounds probably better tho).

Now, I see my main complain was about the `rocm-dkms` structuring (and name), not `rock-dkms` (which obviously, might become optional or even discouraged for many people, and should not be a hard package dependency on any other component - and it appears it isn't, which is good - modulo the udev rules, which probably should be shipped in separate package that is a dependency of `rocm-dkms`, not bundled into `rock-dkms`. Just my guess.).

Anyway, this issue should probably stay more on HIP topic, most notably the README for the HIP installation.

**Comment by mangupta** [comment]
Closing this since the documentation has been updated with instructions regarding packages to be installed for AMD-hcc configuration.
