### ISSUE TITLE
Equivalent to mad24 call in opencl ?

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#85]

**Comment by ekondis** [comment]
There is a __mul24

**Comment by boxerab** [comment]
Thanks. mad24 would be nice to have.

**Comment by adityaatluri** [comment]
Hi,
We didn't add because [cuda](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT) do not support it. I'll add mad24 for next release of HIP. We have ISA `v_mad_u32_u24` and `v_mad_i32_i24`.

If you want it right now, you can add the following IR code to [this file](https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_hc.ll)

```
define i32 @__hip_hc_ir_madi24_int(i32 %a, i32 %b, i32 %c) #1 {
  %1 = tail call i32 asm sideeffect "v_mad_i32_i24 $0, $1, $2, $3","=v,v,v,v"(i32 %a, i32 %b, i32 %c)
  ret i32 %1
}

define i32 @__hip_hc_ir_madu24_int(i32 %a, i32 %b, i32 %c) #1 {
  %1 = tail call i32 asm sideeffect "v_mad_u32_u24 $0, $1, $2, $3","=v,v,v,v"(i32 %a, i32 %b, i32 %c)
  ret i32 %1
}
```
HCC should be able generate binary for the [isa](https://github.com/RadeonOpenCompute/llvm/blob/d59c0756ce8776abe52474cfe61b8e0604fec2d6/test/CodeGen/AMDGPU/mad_uint24.ll)

Don't close the issue yet.

**Comment by ekondis** [comment]
Interesting. Btw, the ROCm v1.4 compiler was able to combine __mul24 with additions to v_mad_xxx_24 instructions something that did not happen with v1.5 in my experiments.

**Comment by scchan** [comment]
@boxerab You could calling hc::__mad24
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/include/hc.hpp#L3201

@ekondis Could you with hc::__mad24 and see if it works for you?  Note that we implemented as a __mul24 followed by an addition and I could see the compiler combining them into mad24.

**Comment by boxerab** [comment]
Thanks, guys! I am just doing some investigation on HIP framework. I'm only going to actually start coding when there is a windows port (or a timeline for that in near future).

**Comment by ekondis** [comment]
@scchan Yes, using hc::__mad24 produces optimum ISA.
e.g. performance numbers on R9-Nano:  hc::__mad24 yields ~7805 GIOPS

**Comment by bensander** [comment]
Closing as hc syntax is available for code targetting ROCm.  If portability to CUDA is desired, use #ifdef __HCC_PLATFORM_HCC__ defines to guard the HC-specific code.
