### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by marmistrz** [ROCm-Developer-Tools/HIP#90]
Hi! Great to see some initiative to try to break the proprietary CUDA's monopoly :) 

As far as I can see, HIP supports either NVIDIA GPUs (using nvcc) or AMD GPUs (using hcc). This makes some of the following cases not covered:

* **Intel GPUs** - many devices do not have a dedicated graphics card and use the Intel HD Graphics GPU. This could make entry for new developers much easier, before they decide that they need a higher-end graphic card, or for those, who are using nouveau for their NVIDIA graphics (nouveau doesn't support compute yet).
* **mobile devices** - they are usually equipped with a Qualcomm Adreno GPU, which supports OpenCL

Besides, when the compute capability arises in the open-source nouveau driver, there's possible that OpenCL will be supported rather than CUDA. [ask nouveau people for their opinion here, though, just a vague guess]

I'm pretty aware of the fact that it's not a top priority issue and completely out of scope for HPC - it's much more important to have portable deep learning libraries (currently there's basically nothing that supports something else than CUDA) - but it would be great to see such support in HIP.

**Comment by sunway513** [comment]
Hi, thanks for the comments on HIP!
If you are looking for OpenCL on ROCm stack, the answer is YES, we've already supported it. More details [here](https://github.com/RadeonOpenCompute/ROCm#to-install-rocm-with-developer-preview-of-opencl).
Also, we are going to release MIOpen library on June.29th. It'll be open source and fully optimized for our ROCm stack. Even better, it provides compatible APIs for both HIP and OpenCL applications.

**Comment by sunway513** [comment]
Thanks for the further explanations. 
We do not have plans to support Intel integrated GPU ourselves. However, HIP is under MIT license, thus, community contribution for different backends would be encouraged.

**Comment by marmistrz** [comment]
Hmm, the Intel GPUs were just an example. I meant adding a generic OpenCL backend, which could be used on anything that supports OpenCL. That would be a whole range of different devices with different architectures. 

This is not planned either?

**Comment by sunway513** [comment]
Since we have both HIP and OpenCL in ROCm open source stack, personally I do not see much benefits from providing a generic OpenCL backend for HIP. 
Community and academic research projects might like this idea better :-)

**Comment by marmistrz** [comment]
It would make HIP code more portable, since it could run on devices other than NVIDIA and AMD, such as mobile phones. That's basically the only benefit.

**Comment by bensander** [comment]
HIP is built on open-standards and open-source software:

  *   The HIP runtime uses the HSA Runtime + some extensions for discrete GPUs and P2P communication.  HSA Runtime is an open standard published by the HSA Foundation.
  *   The HIP compiler is based on LLVM.  Notably, the code generation uses the GCN code generator which is part of upstream LLVM.  HIP generates the ISA directly and does not use intermediate layers such as PTX, HSAIL, or SPIRV.

We used to support an OpenCL backend but found it awkward – you can get something hackish that works for simple cases but it is hard to build a robust solution.   Generally, the issue we saw is that OpenCL is designed more as a standalone programming language rather than a language runtime.  Some of the specific reasons for choosing HSA Runtime and Direct-To-ISA Compilation:

  *   OpenCL kernels can only accept POD types as arguments, so it is challenging to pass complex structures, classes, or functors into kernels.
  *   HSA Runtime APIs support code objects (with embedded vendor-specific ISA) in addition to the intermediate layer (HSAIL in this case).  Those APIs include mechanisms to query symbols, global variables, etc.
  *   HSA Runtime provides low-level control over the dispatch (via AQL packets), which is useful for a language runtime.
  *   Working with any of the intermediate languages (SPIR or HSAIL) was noticeably slower than working directly with LLVMIR.  Some of this was the technical work to add features or new instructions through the additional layers, and some was the process of standards body working groups.

For these reasons we focused on the HSA Runtime and direct-to-isa compilation.  Most vendors already support an LLVM back-end for their target, and for more complex applications using this directly will result in more stable and performant results than generating intermediate layer.   HSA Runtime is designed as a language framework and it shows when you build complex languages on top and run real applications such as TensorFlow.   We use both open-source and open-standard – open-source moves faster (engineers writing code and iterating on it is faster than developing a spec with a working group), but open-standards are useful when you need flexibility to support different implementations (ie the HSA Runtime came from standards body).

**Comment by marmistrz** [comment]
@bensander Sorry for the delayed reply but thanks a lot for the detailed reply! In the light of what you've said, I totally understand your decision. Good luck! :)
